ifeq ($(CONFIG_ARCH_ROCKCHIP), y)

dtb-$(CONFIG_CPU_RK3588) += \
	rk3588-lubancat-generic.dtb \
	rk3588s-lubancat-4.dtb \
	rk3588s-lubancat-4-v1.dtb \
	rk3588s-lubancat-4io.dtb \
	rk3588-lubancat-5.dtb \
	rk3588-lubancat-5-v2.dtb \
	rk3588-lubancat-5io.dtb \
	rk3588-lubancat-5ioi.dtb \

endif

subdir-y	:= $(dts-dirs) overlay

